### ISSUE TITLE
This misses the point of `WeakMap`

### ISSUE THREAD

**Issue by pitust** [polygonplanet/weakmap-polyfill#2]
The point of WeakMap is to get objects held *WEAKLY*. This doesn't and as such, it misses the point.

**Comment by polygonplanet** [comment]
This library is purpose to work JavaScript even if the environment has not native ES2015 WeakMap. We think it's impossible to get objects held weakly without language support.
Note: this will emulate basic WeakMap methods, but this has not completely compatible with es2015+ WeakMap for example [new WeakMap passed with `iterable` argument](https://tc39.es/ecma262/#sec-weakmap-iterable) is not supported). Thanks your review, We welcome PR!

**Comment by pitust** [comment]
It IS Possible to hold objects weakly:
`
function hold(k, v) {
k.weakval = v;
}
function get(k) {
return k.weakval;
}
function set(k, v) {
k.weakval = vn
}
`

**Comment by yvele** [comment]
Yes I recommend using core-js https://github.com/zloirock/core-js#caveats-when-using-collections-polyfill

> Weak-collections polyfill stores values as hidden properties of keys. It works correct and not leak in most cases. However, it is desirable to store a collection longer than its keys.
